import assert from 'node:assert/strict';
import test from 'node:test';
import { AGENT_PROFILE_DEFINITIONS, AGENT_PROMPT_SEED_REVISION, FLOW_AGENT_IDS } from './agent-profile';

test('ships rigorous versioned seed prompts for every flow Agent', () => {
  assert.equal(AGENT_PROMPT_SEED_REVISION, 26);
  for (const agentId of FLOW_AGENT_IDS) {
    const prompt = AGENT_PROFILE_DEFINITIONS[agentId].prompt;
    assert.ok(prompt.length >= 450, `${agentId} seed prompt is too small to define a reliable role contract`);
    assert.match(prompt, /# 角色目标/, agentId);
    assert.match(prompt, /# (?:完成条件|判定规则)/, agentId);
    assert.match(prompt, /# (?:决策边界|禁止事项)/, agentId);
  }
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /现有实现已经满足规格/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /当前实际业务状态、当前应有的业务语义和用户期望的目标状态/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /如何拆分交付单元由后续交付规划 Agent 决定/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /request-clarification/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /每次启动先.*requirement-context status/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /信息不足时澄清，不得猜测分类/);
  assert.doesNotMatch(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /\bintake\b/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /用户最新的明确业务决策必须在原稳定 key 上继承/);
  assert.doesNotMatch(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /数据库文档/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /bug 表示 actual 偏离已有明确 expected.*feature 表示主动改变.*tech 主要改变.*other 只用于/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /代码只是理解当前实现的一种证据，不等同于完整业务事实/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /具体调查方向由当前项目的领域、证据和业务结构决定，不套用固定行业清单/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /识别影响不等于自动扩大范围/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /错误结论必须带理由 dismiss.*显式 supersede/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /实质改变业务目标、业务规则、参与者、范围、分类或验收结果的最少问题/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /实现偏好、技术细节和可自行调查的事实不得询问/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /不得修改工作区中的任何文件，不得提交代码/);
  assert.match(AGENT_PROFILE_DEFINITIONS['story-splitter-agent'].prompt, /每次启动先.*delivery-plan status/);
  assert.match(AGENT_PROFILE_DEFINITIONS['story-splitter-agent'].prompt, /稳定 unit key/);
  assert.match(AGENT_PROFILE_DEFINITIONS['story-splitter-agent'].prompt, /delivery-plan complete/);
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /完整 decisionTree/);
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /重大技术决策/);
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /禁止使用 safe_default/);
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /analysis status/);
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /原 decision key/);
  assert.match(AGENT_PROFILE_DEFINITIONS['repro-agent'].prompt, /每次启动先.*reproduction status/);
  assert.match(AGENT_PROFILE_DEFINITIONS['repro-agent'].prompt, /reproduction complete/);
  assert.match(AGENT_PROFILE_DEFINITIONS['repro-agent'].prompt, /reproduction request-alignment/);
  assert.match(AGENT_PROFILE_DEFINITIONS['repro-agent'].prompt, /必须由人对齐/);
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /不要为了制造 diff/);
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /工作区已有其他未提交内容不是跳过 commit 的理由/);
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /提交成功后记录当前 HEAD.*implementation complete/);
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /只能暂存本轮相关改动/);
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /implementation status/);
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /implementation complete/);
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /原 request key/);
  assert.match(AGENT_PROFILE_DEFINITIONS['test-agent'].prompt, /verification status/);
  assert.match(AGENT_PROFILE_DEFINITIONS['test-agent'].prompt, /verification pass/);
  assert.match(AGENT_PROFILE_DEFINITIONS['test-agent'].prompt, /原 recovery id/);
  assert.match(AGENT_PROFILE_DEFINITIONS['review-agent'].prompt, /逐条说明如何处理/);
  assert.match(AGENT_PROFILE_DEFINITIONS['review-agent'].prompt, /Application 只向前追加交付单元/);
  assert.match(AGENT_PROFILE_DEFINITIONS['review-agent'].prompt, /不得返回 changes_requested/);
  assert.match(AGENT_PROFILE_DEFINITIONS['review-agent'].prompt, /每次启动先.*review status/);
  assert.match(AGENT_PROFILE_DEFINITIONS['review-agent'].prompt, /review complete/);
  assert.match(AGENT_PROFILE_DEFINITIONS['review-agent'].prompt, /稳定 evidence key/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /Triage/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /Verify/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /scope_addition/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /bug/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /不返回 targetStage、targetAgent、rewindTo/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /currentFeedbackBatch/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /追加交付单元/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /feedback status/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /feedback triage-complete/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /feedback resolve/);
});
