import assert from 'node:assert/strict';
import test from 'node:test';
import { AGENT_PROFILE_DEFINITIONS, AGENT_PROMPT_SEED_REVISION, FLOW_AGENT_IDS } from './agent-profile';

test('ships rigorous V11 seed prompts for every flow Agent', () => {
  assert.equal(AGENT_PROMPT_SEED_REVISION, 11);
  for (const agentId of FLOW_AGENT_IDS) {
    const prompt = AGENT_PROFILE_DEFINITIONS[agentId].prompt;
    assert.ok(prompt.length >= 450, `${agentId} seed prompt is too small to define a reliable role contract`);
    assert.match(prompt, /# 角色目标/, agentId);
    assert.match(prompt, /# (?:完成条件|判定规则)/, agentId);
    assert.match(prompt, /# (?:决策边界|禁止事项)/, agentId);
  }
  assert.match(AGENT_PROFILE_DEFINITIONS['idea-context-agent'].prompt, /DISCOVERY → \[RESEARCH\] → CLARIFICATION PROPOSAL → CLARIFICATION RESOLUTION → SYNTHESIS → FINALIZE/);
  assert.match(AGENT_PROFILE_DEFINITIONS['idea-context-agent'].prompt, /必须实际使用 Web Search/);
  assert.match(AGENT_PROFILE_DEFINITIONS['idea-context-agent'].prompt, /CLARIFICATION RESOLUTION 才读取.*自动决策强度/);
  assert.match(AGENT_PROFILE_DEFINITIONS['idea-context-agent'].prompt, /提出和回答必须分开/);
  assert.match(AGENT_PROFILE_DEFINITIONS['idea-context-agent'].prompt, /HUMAN 与 Agent 答案、空问题树和完全自主模式.*穷尽性审查/);
  assert.match(AGENT_PROFILE_DEFINITIONS['idea-context-agent'].prompt, /Frontier.*整个 frontier.*下一轮/s);
  assert.match(AGENT_PROFILE_DEFINITIONS['idea-context-agent'].prompt, /不是只判断.*答案有没有引出新问题.*主动寻找仍未确认/s);
  assert.match(AGENT_PROFILE_DEFINITIONS['idea-context-agent'].prompt, /frontier 为空/);
  assert.match(AGENT_PROFILE_DEFINITIONS['business-design-agent'].prompt, /DECISION PROPOSAL.*DECISION RESOLUTION/);
  assert.match(AGENT_PROFILE_DEFINITIONS['business-design-agent'].prompt, /EXPLORATION → \[RESEARCH\].*DECISION PROPOSAL/);
  assert.match(AGENT_PROFILE_DEFINITIONS['business-design-agent'].prompt, /RESEARCH BASIS/);
  assert.match(AGENT_PROFILE_DEFINITIONS['business-design-agent'].prompt, /自动决策强度/);
  assert.match(AGENT_PROFILE_DEFINITIONS['business-design-agent'].prompt, /Agent 自主答案或空问题树.*完成标准/);
  assert.match(AGENT_PROFILE_DEFINITIONS['business-design-agent'].prompt, /拷问标准.*反例/);
  assert.match(AGENT_PROFILE_DEFINITIONS['business-design-agent'].prompt, /当前 frontier.*同一批次.*下一轮/s);
  assert.match(AGENT_PROFILE_DEFINITIONS['business-design-agent'].prompt, /不是只判断.*所有需要确认/s);
  assert.match(AGENT_PROFILE_DEFINITIONS['requirement-spec-agent'].prompt, /AS IS、TO BE、ACTORS、SCENARIOS/);
  assert.match(AGENT_PROFILE_DEFINITIONS['spec-review-agent'].prompt, /intent、business_design 或 specification/);
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /现有实现已经满足承诺/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /AS-IS → DECISION TREE · PROPOSE → DECISION TREE · RESOLVE → ANSWER REVIEW → TO-BE → Impact Scan → SCOPE → Acceptance → Finalize/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /PROPOSE 与 RESOLVE 必须分开/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /自动决策强度处理 Agent 节点/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /每轮 HUMAN 或 Agent 答案全部关闭后必须进入 ANSWER REVIEW/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /拷问标准.*静默假设.*反例/s);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /当前 frontier.*下一轮/s);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /不是只判断.*所有需要确认/s);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /request-clarification/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /第一条草稿命令必须是 requirement-context status/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /继续执行命令返回的下一工作包/);
  assert.doesNotMatch(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /\bintake\b/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /已有用户决定必须按原 key 继承/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /bug 表示 Actual 偏离已有明确 Expected.*feature 表示主动改变.*tech 主要改变.*other 只用于/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /没有独立业务文档时，应深入代码和真实入口还原当前行为/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /持久化内容必须提升为参与者、触发条件、业务规则、状态变化和可观察结果/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /代码是获取知识的手段，不是需求上下文的表达语言/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /需求规格与代码呈现不同业务逻辑时，必须同时记录 Expected 与 Actual/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /technical.*作为 Analysis Obligations/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /目标不是问题越少越好.*穷尽职责内真实语义分叉/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /批量处理当前 frontier.*节点同轮提出.*下一轮/s);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /互斥选项、各自业务后果、推荐选项及理由/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /输入的需求规格和业务方案与当前项目的真实业务行为进行核对/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /规格与代码或运行中的业务逻辑冲突/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /不要主动提出超出输入业务方案的新产品形态、替代目标或增值方案/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /TO-BE 和 SCOPE 是正式产物/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /完全自主模式必须自行关闭全部活动节点/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /识别影响不等于扩大范围/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /会形成独立业务结果的影响不得暗中并入本轮/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /错误结论带理由 dismiss.*显式 supersede/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /能从上下文和项目证据确定的事实不得询问用户/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /不得以“合理性”为名用 Agent 偏好覆盖已确定的业务语义/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /如果规格与代码现状不一致.*SCOPE 或交付单元拆分/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /不得修改工作区文件或提交代码/);
  assert.match(AGENT_PROFILE_DEFINITIONS['story-splitter-agent'].prompt, /每次启动先.*delivery-plan status/);
  assert.match(AGENT_PROFILE_DEFINITIONS['story-splitter-agent'].prompt, /稳定 unit key/);
  assert.match(AGENT_PROFILE_DEFINITIONS['story-splitter-agent'].prompt, /change.*preserve.*technical.*acceptance/);
  assert.match(AGENT_PROFILE_DEFINITIONS['story-splitter-agent'].prompt, /无法证明可以独立时采用保守的较大闭环/);
  assert.match(AGENT_PROFILE_DEFINITIONS['story-splitter-agent'].prompt, /不通过提问或阶段回退/);
  assert.match(AGENT_PROFILE_DEFINITIONS['story-splitter-agent'].prompt, /delivery-plan complete/);
  assert.equal(AGENT_PROFILE_DEFINITIONS['analyst-agent'].label, '交付分析 Agent');
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /Do It Twice/);
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /不是需要持久化的过程模板/);
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /当前交付单元及其上游业务语义是本阶段必须履行的承诺/);
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /不同选择是否会产生不同的业务语义、用户可观察结果、信息层级、交互路径/);
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /先提出、再回答/);
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /除非当前 RESOLVE 工作包明确给出完全自主权限.*不能代替产品决定权/);
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /自动决策策略只由 DECISION TREE · RESOLVE 工作包提供/);
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /ANSWER REVIEW：无论答案来自 HUMAN、上游、项目证据还是 Agent 权限/);
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /拷问标准.*静默假设.*唯一验证 Oracle/s);
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /Frontier.*整个 frontier.*下一轮/s);
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /不是只判断.*所有交付前必须确认/s);
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /只有完全自主模式允许 Agent.*自行决定产品语义/);
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /任何会约束 Dev 或 Test 的方案必须先在决策树中登记/);
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /保持原决定的稳定语义身份/);
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /让独立 Test Agent 建立唯一的业务 Oracle/);
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /两个合理的 Dev Agent.*实质差异的用户可观察结果/);
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /两个独立的 Test Agent.*不同的正确预期/);
  assert.doesNotMatch(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /delivery-analysis (?:status|complete|request-clarification)/);
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /不得修改工作区文件或提交代码/);
  assert.match(AGENT_PROFILE_DEFINITIONS['repro-agent'].prompt, /候选异常的事实确认者/);
  assert.match(AGENT_PROFILE_DEFINITIONS['repro-agent'].prompt, /Reported Expected.*Observed Actual/);
  assert.match(AGENT_PROFILE_DEFINITIONS['repro-agent'].prompt, /Observed Actual 只证明在已记录的环境、版本、时间、数据和触发条件下/);
  assert.match(AGENT_PROFILE_DEFINITIONS['repro-agent'].prompt, /项目文档若明确承担规范性职责.*Expected 的候选证据交给后续业务对齐/);
  assert.match(AGENT_PROFILE_DEFINITIONS['repro-agent'].prompt, /最小充分差异样例/);
  assert.match(AGENT_PROFILE_DEFINITIONS['repro-agent'].prompt, /本地重新制造不是确认问题的唯一方式/);
  assert.match(AGENT_PROFILE_DEFINITIONS['repro-agent'].prompt, /根因假设.*不是本阶段的交付物、完成门槛或后续实现方案/);
  assert.match(AGENT_PROFILE_DEFINITIONS['repro-agent'].prompt, /不要把事实补充包装成产品决策/);
  assert.match(AGENT_PROFILE_DEFINITIONS['repro-agent'].prompt, /无法确认不等于证明问题不存在/);
  assert.match(AGENT_PROFILE_DEFINITIONS['repro-agent'].prompt, /确认有条件、有证据的 Observed Actual.*不得把它上升为权威业务语义/);
  assert.match(AGENT_PROFILE_DEFINITIONS['repro-agent'].prompt, /不决定这个 Actual 是否符合现行业务规则、最终 TO-BE、需求类型/);
  assert.match(AGENT_PROFILE_DEFINITIONS['repro-agent'].prompt, /不得修改目标仓库中的任何持久文件/);
  assert.match(AGENT_PROFILE_DEFINITIONS['repro-agent'].prompt, /真实环境只做已经授权的非破坏性观察/);
  assert.match(AGENT_PROFILE_DEFINITIONS['repro-agent'].prompt, /不输出 bug 或 not-bug 的业务裁决/);
  assert.match(AGENT_PROFILE_DEFINITIONS['repro-agent'].prompt, /交给后续业务对齐/);
  assert.doesNotMatch(AGENT_PROFILE_DEFINITIONS['repro-agent'].prompt, /reproduction (?:status|complete|request-alignment|validate)/);
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /当前交付单元的实现负责人/);
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /重试或恢复时继承仍然有效的已有进展和证据/);
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /最小充分、结构完整且可维护.*不以最少代码行或最小 diff 为目标/);
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /在已关闭的业务和核心技术边界内行使工程自主权/);
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /可以在当前交付范围内进行必要重构/);
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /开发者自验证.*不能代替验证 Agent.*最终验收/);
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /报告分析契约冲突.*由 Application 决定后续路径/);
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /不得静默改变承诺、直接向用户提问或自行选择 goto、回退阶段/);
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /有代码变化时按目标仓库规范形成边界清晰、可审查、可追溯的独立提交/);
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /不因分支、HEAD、其他 Commit 或无关未提交变化拒绝工作/);
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /不向验证 Agent 传递测试目标、测试步骤或通过结论/);
  assert.doesNotMatch(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /implementation (?:status|complete)/);
  assert.doesNotMatch(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /每次启动先|每完成一个文件|每个真实命令执行后|当前 HEAD|原 request key/);
  assert.match(AGENT_PROFILE_DEFINITIONS['test-agent'].prompt, /独立验证负责人/);
  assert.match(AGENT_PROFILE_DEFINITIONS['test-agent'].prompt, /PLAN → EXECUTE → EVIDENCE REVIEW → FINALIZE/);
  assert.match(AGENT_PROFILE_DEFINITIONS['test-agent'].prompt, /PLAN 只从冻结契约/);
  assert.match(AGENT_PROFILE_DEFINITIONS['test-agent'].prompt, /EXECUTE 按冻结计划逐项执行真实黑盒测试/);
  assert.match(AGENT_PROFILE_DEFINITIONS['test-agent'].prompt, /EVIDENCE REVIEW 独立复核证据/);
  assert.match(AGENT_PROFILE_DEFINITIONS['test-agent'].prompt, /每项交付单元验收语义至少要有一个从真实前端覆盖的场景/);
  assert.match(AGENT_PROFILE_DEFINITIONS['test-agent'].prompt, /API 场景.*不能脱离业务期望只验证接口实现细节/);
  assert.match(AGENT_PROFILE_DEFINITIONS['test-agent'].prompt, /API 场景.*可以独立形成实现失败、规格问题或环境阻塞的有效反例/);
  assert.match(AGENT_PROFILE_DEFINITIONS['test-agent'].prompt, /浏览器、账号、设备条件或测试数据等执行资源不可获得时.*验证协助/);
  assert.match(AGENT_PROFILE_DEFINITIONS['test-agent'].prompt, /用户可以补充缺失条件，也可以代为执行并提供实际观察/);
  assert.match(AGENT_PROFILE_DEFINITIONS['test-agent'].prompt, /系统阻塞只用于 Runner、CLI、浏览器控制或 Application 自身故障/);
  assert.doesNotMatch(AGENT_PROFILE_DEFINITIONS['test-agent'].prompt, /凡用于判定.*都必须由.*前端/);
  assert.match(AGENT_PROFILE_DEFINITIONS['test-agent'].prompt, /在执行待测业务行为之前，先冻结由 Oracle 推导的业务主张与预期/);
  assert.match(AGENT_PROFILE_DEFINITIONS['test-agent'].prompt, /每个活动场景最终都必须有通过、失败或阻塞结论/);
  assert.match(AGENT_PROFILE_DEFINITIONS['test-agent'].prompt, /目标是寻找反例，而不是证明开发者声明/);
  assert.match(AGENT_PROFILE_DEFINITIONS['test-agent'].prompt, /不得修改目标仓库中的任何持久文件/);
  assert.match(AGENT_PROFILE_DEFINITIONS['test-agent'].prompt, /Dev Agent 的完成声明、自检、开发记录、变更说明、Commit message、恢复声明及其选择的测试都不能作为 Oracle 或通过依据/);
  assert.doesNotMatch(AGENT_PROFILE_DEFINITIONS['test-agent'].prompt, /读取.*开发结果/);
  assert.doesNotMatch(AGENT_PROFILE_DEFINITIONS['test-agent'].prompt, /verification (?:status|pass|fail|block|request-input)/);
  assert.match(AGENT_PROFILE_DEFINITIONS['test-agent'].prompt, /复用原稳定身份/);
  assert.match(AGENT_PROFILE_DEFINITIONS['review-agent'].prompt, /最终事实对账与结卡报告负责人/);
  assert.match(AGENT_PROFILE_DEFINITIONS['review-agent'].prompt, /FACT RECONCILIATION → CLOSURE ASSESSMENT/);
  assert.match(AGENT_PROFILE_DEFINITIONS['review-agent'].prompt, /FORWARD DELIVERY UNITS → FINALIZE/);
  assert.match(AGENT_PROFILE_DEFINITIONS['review-agent'].prompt, /不再经过 Story Splitter/);
  assert.match(AGENT_PROFILE_DEFINITIONS['review-agent'].prompt, /原始业务目标和验收语义.*最终用户可观察结果/);
  assert.match(AGENT_PROFILE_DEFINITIONS['review-agent'].prompt, /检查多个交付单元组合后的最终事实/);
  assert.match(AGENT_PROFILE_DEFINITIONS['review-agent'].prompt, /不重新执行测试.*结卡缺口/);
  assert.match(AGENT_PROFILE_DEFINITIONS['review-agent'].prompt, /只消费 Feedback Agent 已经完成分流和独立验证的结论/);
  assert.match(AGENT_PROFILE_DEFINITIONS['review-agent'].prompt, /报告更正工作是唯一例外.*候选新版本.*Feedback Agent 独立验证/);
  assert.match(AGENT_PROFILE_DEFINITIONS['review-agent'].prompt, /严格区分结卡缺口与残余风险/);
  assert.match(AGENT_PROFILE_DEFINITIONS['review-agent'].prompt, /标准章节只是表达模板，不是角色目标/);
  assert.match(AGENT_PROFILE_DEFINITIONS['review-agent'].prompt, /不得创造新的交付事实/);
  assert.match(AGENT_PROFILE_DEFINITIONS['review-agent'].prompt, /交由 Application 决定如何向前追加验证或修订/);
  assert.match(AGENT_PROFILE_DEFINITIONS['review-agent'].prompt, /若事实链不闭合，必须声明结卡缺口/);
  assert.doesNotMatch(AGENT_PROFILE_DEFINITIONS['review-agent'].prompt, /review (?:status|complete|request-input|section|evidence)/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /Triage/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /Verify/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /scope_addition/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /bug/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /不返回 targetStage、targetAgent、rewindTo/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /currentFeedbackBatch/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /追加交付单元/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /feedback status/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /feedback triage-complete/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /feedback resolve/);
});
