import assert from 'node:assert/strict';
import test from 'node:test';
import { AGENT_PROFILE_DEFINITIONS, AGENT_PROMPT_SEED_REVISION, FLOW_AGENT_IDS } from './agent-profile';

test('ships rigorous versioned seed prompts for every flow Agent', () => {
  assert.equal(AGENT_PROMPT_SEED_REVISION, 25);
  for (const agentId of FLOW_AGENT_IDS) {
    const prompt = AGENT_PROFILE_DEFINITIONS[agentId].prompt;
    assert.ok(prompt.length >= 450, `${agentId} seed prompt is too small to define a reliable role contract`);
    assert.match(prompt, /# 角色目标/, agentId);
    assert.match(prompt, /# (?:完成条件|判定规则)/, agentId);
    assert.match(prompt, /# (?:决策边界|禁止事项)/, agentId);
  }
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /现有实现已经满足规格/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /目标、整体范围、主要参与者、Bug\/非 Bug 分类或最终验收结果/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /如何拆分交付单元完全由后续交付规划 Agent 决定/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /request-clarification/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /每次启动先.*requirement-context status/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /不得为了通过校验猜测临时分类/);
  assert.doesNotMatch(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /\bintake\b/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /用户最新的明确指令和已经回答的需求级问题具有最高优先级/);
  assert.doesNotMatch(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /数据库文档/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /feature 是新增或改变.*bug 是现有可观察行为偏离.*tech 的主要目标是.*other 只用于/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /用户、运营者、开发者或外部系统最终能够验证到什么变化/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /事实来源必须可定位到用户输入或答复、Context ref、仓库相对路径与符号/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /探索到足以确认现有可观察行为.*后立即停止/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /实质改变需求语义的最少问题/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /不询问偏好性问题、实现细节或可自行验证的事实/);
  assert.match(AGENT_PROFILE_DEFINITIONS['backlog-agent'].prompt, /不得修改工作区中的任何文件，不得提交代码/);
  assert.match(AGENT_PROFILE_DEFINITIONS['story-splitter-agent'].prompt, /每次启动先.*delivery-plan status/);
  assert.match(AGENT_PROFILE_DEFINITIONS['story-splitter-agent'].prompt, /稳定 unit key/);
  assert.match(AGENT_PROFILE_DEFINITIONS['story-splitter-agent'].prompt, /delivery-plan complete/);
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /完整 decisionTree/);
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /重大技术决策/);
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /禁止使用 safe_default/);
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /analysis status/);
  assert.match(AGENT_PROFILE_DEFINITIONS['analyst-agent'].prompt, /原 decision key/);
  assert.match(AGENT_PROFILE_DEFINITIONS['repro-agent'].prompt, /每次启动先.*reproduction status/);
  assert.match(AGENT_PROFILE_DEFINITIONS['repro-agent'].prompt, /reproduction complete/);
  assert.match(AGENT_PROFILE_DEFINITIONS['repro-agent'].prompt, /reproduction request-alignment/);
  assert.match(AGENT_PROFILE_DEFINITIONS['repro-agent'].prompt, /必须由人对齐/);
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /不要为了制造 diff/);
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /工作区已有其他未提交内容不是跳过 commit 的理由/);
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /提交成功后记录当前 HEAD.*implementation complete/);
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /只能暂存本轮相关改动/);
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /implementation status/);
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /implementation complete/);
  assert.match(AGENT_PROFILE_DEFINITIONS['dev-agent'].prompt, /原 request key/);
  assert.match(AGENT_PROFILE_DEFINITIONS['test-agent'].prompt, /verification status/);
  assert.match(AGENT_PROFILE_DEFINITIONS['test-agent'].prompt, /verification pass/);
  assert.match(AGENT_PROFILE_DEFINITIONS['test-agent'].prompt, /原 recovery id/);
  assert.match(AGENT_PROFILE_DEFINITIONS['review-agent'].prompt, /逐条说明如何处理/);
  assert.match(AGENT_PROFILE_DEFINITIONS['review-agent'].prompt, /Application 只向前追加交付单元/);
  assert.match(AGENT_PROFILE_DEFINITIONS['review-agent'].prompt, /不得返回 changes_requested/);
  assert.match(AGENT_PROFILE_DEFINITIONS['review-agent'].prompt, /每次启动先.*review status/);
  assert.match(AGENT_PROFILE_DEFINITIONS['review-agent'].prompt, /review complete/);
  assert.match(AGENT_PROFILE_DEFINITIONS['review-agent'].prompt, /稳定 evidence key/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /Triage/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /Verify/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /scope_addition/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /bug/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /不返回 targetStage、targetAgent、rewindTo/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /currentFeedbackBatch/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /追加交付单元/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /feedback status/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /feedback triage-complete/);
  assert.match(AGENT_PROFILE_DEFINITIONS['feedback-agent'].prompt, /feedback resolve/);
});
